### ISSUE TITLE
Website docs instruct new users to download v2.9

### ISSUE THREAD

**Issue by tim-seoss** [mitogen-hq/mitogen#1008]
The getting started docs at: https://mitogen.networkgenomics.com/ansible_detailed.html
instruct the user to:

"Download and extract https://networkgenomics.com/try/mitogen-0.2.9.tar.gz"

... these instructions are pointed to by the README.md in the root of the git repo:

`[Please see the documentation](https://mitogen.networkgenomics.com/)`

**Comment by moreati** [comment]
Duplicate of #962
