### ISSUE TITLE
Idea: Split mitogen and ansible-mitogen

### ISSUE THREAD

**Issue by guenhter** [mitogen-hq/mitogen#1009]
Just an idea: Would it make sense to split mitogen and the ansible integration into separate repos? 
Mitogen is then mainly maintained by the core mitogen team where the ansible integration could be opened up a little bit more to have more core maintainers? What do you think?

**Comment by amarao** [comment]
I've tried to read, but it's really hard. Both ansible_mitogen and mitogen are extremely complex.

**Comment by moreati** [comment]
It's somethnig I've considered, but I'm not convinced it would help. There isn't a clean interface between mitogen and ansible_mitogen - they're both tightly coupled, so I expect they couldn't be released intedpendently and ahving them in seperate repos/packages would just increase maintenance cost.

**Comment by guenhter** [comment]
Oh, thats to bad. I'll close this then for now. Thx for the fast response.
