### ISSUE TITLE
ansible-core 2.15 support

### ISSUE THREAD

**Issue by pandalec** [mitogen-hq/mitogen#1021]
Like the other issues for 2.13 and 2.14, another one for the current stable ansible version. Would be nice to speed up our Ansible with Mitogen

**Comment by AlexanderKls** [comment]
We have also updated to Ansible 2.15 and hope that Mitogen will support this version.

**Comment by zerwes** [comment]
#974 ... #966 ... #929 ... we used mitogen for a long time, but - sad to say - since #952 we gave up ... reliability comes before speed ...

**Comment by adpavlov** [comment]
voting as well

**Comment by YanFenGuo** [comment]
Any estimation when can we get Ansible 2.15 supported?

**Comment by moreati** [comment]
Mitogen 0.3.7 is out https://pypi.org/project/mitogen/0.3.7/ with Ansible 8 and 9 support.
