### ISSUE TITLE
Download link points to an HTTP 404 (unreleased version)

### ISSUE THREAD

**Issue by moreati** [mitogen-hq/mitogen#1028]
Since deploying #1026 the download link on https://mitogen.networkgenomics.com/ansible_detailed.html points to https://networkgenomics.com/try/mitogen-0.3.5.dev0.tar.gz. This version is unreleased, hence the tarball doesn't exist

refs #962

**Comment by moreati** [comment]
```
➜  mitogen git:(docs-master) ✗ wget https://networkgenomics.com/try/mitogen-0.3.5.dev0.tar.gz
--2023-10-06 11:54:30--  https://networkgenomics.com/try/mitogen-0.3.5.dev0.tar.gz
Resolving networkgenomics.com (networkgenomics.com)... 157.90.33.51
Connecting to networkgenomics.com (networkgenomics.com)|157.90.33.51|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://files.pythonhosted.org/packages/source/m/mitogen/mitogen-0.3.5.dev0.tar.gz [following]
--2023-10-06 11:54:32--  https://files.pythonhosted.org/packages/source/m/mitogen/mitogen-0.3.5.dev0.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 2a04:4e42:f::311, 151.101.61.55
Connecting to files.pythonhosted.org (files.pythonhosted.org)|2a04:4e42:f::311|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-06 11:54:32 ERROR 404: Not Found.
```

**Comment by moreati** [comment]
Options/considerations
- base docs-master on stable branch, rather than master
- calculate latest release by querying Github or PyPI, rather than what is in checked out code
- is it worth removing the 301 redirect, pointing directly to PyPI instead?
- can the installation instructions be switched to `pip install mitogen`, rather than using `wget ...`?

**Comment by TheNotary** [comment]
I'm getting this too.  It might be worth listing these things right here in github

https://github.com/marketplace/actions/publish-a-release

This workaround fixed the issue for me

```
wget https://networkgenomics.com/try/mitogen-0.3.4.tar.gz
```

**Comment by jxc876** [comment]
Getting the same :(

**Comment by Driaan** [comment]
cant download https://networkgenomics.com/try/mitogen-0.3.4.tar.gz either?

**Comment by moreati** [comment]
Currently using Sphinx 2.1.2, a 2019 vintage with [limited linkcheck options](https://github.com/sphinx-doc/sphinx/blob/v2.1.2/sphinx/builders/linkcheck.py#L317-L321). Latest Sphinx 7.2.6 has [more options](https://github.com/sphinx-doc/sphinx/blob/v7.2.6/sphinx/builders/linkcheck.py#L614-L622), probably want them for finer grained redirect checking/skipping.

**Comment by moreati** [comment]
@Driaan networkgenomics.com appears to be down. Use https://pypi.org/project/mitogen/0.3.4/#files instead, this is where the redirect would have gone to.

**Comment by moreati** [comment]
https://mitogen.networkgenomics.com/ansible_detailed.html now points directly to release 0.3.4 on PyPI. No more redirect, and no more 0.3.5dev mentions
