### ISSUE TITLE
Mitogen realeses should not include .ci and .github folder

### ISSUE THREAD

**Issue by eamanu** [mitogen-hq/mitogen#656]
Hello,

I am working on the packaging on Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942853

I could notice that the releases of mitogen have .ci/ and .github/ folders. They
are there for any particular reason? Could be possible not including in the 
releases?

**Comment by moreati** [comment]
Recent releases (e.g. https://pypi.org/project/mitogen/0.3.4/) don't contain .ci or .github.
