### ISSUE TITLE
Travis tests intermittently fail with an extra process error

### ISSUE THREAD

**Issue by s1113950** [mitogen-hq/mitogen#688]
While working on https://github.com/dw/mitogen/pull/658 I noticed this would happen sometimes:
```
======================================================================
ERROR: tearDownClass (doas_test.DoasTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dw/mitogen/tests/testlib.py", line 529, in tearDownClass
    cls.dockerized_ssh.check_processes()
  File "/home/travis/build/dw/mitogen/tests/testlib.py", line 478, in check_processes
    counts
AssertionError: Docker container 'mitogen-test-e71a28532b8fc46f' contained extra running processes after test completed: {u'doas <defunct>': 1, u'ps': 1, u'sshd': 1}
```

Example:
https://github.com/dw/mitogen/pull/658/commits/90d51fcbbd6eb07f5bdb1bdbf6f57ed97013401c this commit passed travis
The commit right after to remove debug logging again failed travis: https://github.com/dw/mitogen/pull/658/commits/e1382861854f38b1736ac598eb70e58beb341c08
even though previously without `-vvv` travis passed here: https://github.com/dw/mitogen/pull/658/commits/e85720f4d5cdff59d952eae67ec6bf85702a10ba

It seems unrelated to changes made in the PR, but will need to investigate further to be sure

**Comment by moreati** [comment]
Duplicates #694
