### ISSUE TITLE
will mitogen keep being maintained alongside operon?

### ISSUE THREAD

**Issue by anarcat** [mitogen-hq/mitogen#751]
I have just noticed @dw [announced a project](https://sweetness.hmmz.org/2019-10-28-operon.html) called [Operon](https://networkgenomics.com/operon/) which, according to the website:

> highly compatible replacement for Ansible® Engine delivering uncompromising scalability for UNIX networks, dramatically increasing performance and maximum achievable run size

This seems to be similar to the work done here in Ansible Mitogen, so I wonder what that means for the fate of the mitogen project as a whole.

Will mitogen be maintained in the long term?

In particular, will mitogen without Ansible still be supported as a use case in the long term?

I see that another maintainer (@s1113950) has access to the repository here, which is reassuring, but I am worried that @dw hasn't been very active on GitHub since those announcements. Operon seems to be a "private source" (GPL, but no public source release or collaboration) project, so I hope you will understand if I have some some concerns about the fate of the project here.

Thanks for this truly enlightening and brilliant piece of software. :)

**Comment by s1113950** [comment]
Hello! 👋 

> Will mitogen be maintained in the long term?

As of now, I don't plan on stopping support of Mitogen. If Operon is meant to replace Mitogen then that might change, but I'm not sure if that's Operon's intended purpose 🤔 (@dw if you could weigh in here that'd be great 😄 ). The only thing I don't have access to is PyPi for pushing new versions of Mitogen, so  the best I can do is tag a new release on the repo itself. Long term, if @dw intends to focus on Operon exclusively then either I'll need to get PyPi access or I'll have to come up with another solution to do more releases. 

> In particular, will mitogen without Ansible still be supported as a use case in the long term?

I mainly use Mitogen with Ansible, but any change that goes into the `ansible_mitogen` portion of the repo also is tested alongside the main `mitogen` portion. If anything breaks along the way I make sure to fix it up :)

**Comment by madrover** [comment]
> The only thing I don't have access to is PyPi for pushing new versions of Mitogen, so the best I can do is tag a new release on the repo itself.

Now I understand why there hasn't been any new release for such a long despite all the work that @s1113950 has been doing (thanks for that btw!)

I'm pretty excited to see that #715 is getting closer so we get Ansible 2.10 support! Sadly, I'm being forced to start ditching Mitogen due the lack of package updates and I'm missing it greatly. Hopefully @dw can grant access to PyPi to the community so the project can still be properly maintained.

**Comment by anarcat** [comment]
> Hopefully @dw can grant access to PyPi to the community so the project can still be properly maintained.

Having been in that position (in the @linkchecker) project, I'd say it's a really important step to take. Otherwise it's a tough uphill battle to reclaim those names...

**Comment by dw** [comment]
I think the original question here has been answered. Glad to see folk care about the continuance of the project!
