### ISSUE TITLE
Should we package as a Python wheel?

### ISSUE THREAD

**Issue by moreati** [mitogen-hq/mitogen#799]
Mainly a minor convenience to consumers installing from PyPI. Would require some CI plumbing to ensure it's tested.

Low priority, mainly filed as a placeholder, in case someone asks.

**Comment by moreati** [comment]
Related: in `setup.cfg` we might be able to declare

```ini
[bdist_wheel]
universal=1
```

**Comment by RonnyPfannschmidt** [comment]
As all modern pip's will build wheels on installation, this is practically necessary anyway, it's certain to happen for a significant portion of the users and should be tested

**Comment by moreati** [comment]
I plan to release 0.2.10rc1 and 0.3.0rc1 as sdist and universal wheel.

**Comment by moreati** [comment]
Release of rc1 happened, no complaints so far
