### ISSUE TITLE
Mac Ansible 2.10 tests are faster than Mac Ansible + Mitogen 2.10 tests

### ISSUE THREAD

**Issue by s1113950** [mitogen-hq/mitogen#804]
This should be fixed 🤔 gotta investigate this, maybe it's because the first mac job installed things that the second mac job doesn't have to or something.

**Comment by moreati** [comment]
Did you see https://github.com/mitogen-hq/mitogen/commit/bb271d8d004a3ea21fd53347406e1368e4746bc8? It tags some Ansible tasks that have 100s of repetitions as "resource_intensive", and skips them on the vanilla Ansible test.

**Comment by s1113950** [comment]
Ahh, 🤦 . Do we know how much faster things are now that ansible + mitogen isn't running the same test as vanilla ansible? Maybe it'd be a good idea to add another 2 test cases where ansible + mitogen ran the same tests as vanilla ansible so it'd be easier to test if we made a regression somewhere 😅
