### ISSUE TITLE
ansible-core 2.11 support?

### ISSUE THREAD

**Issue by shane-axiom** [mitogen-hq/mitogen#834]
Hi, I don't see an existing issue so creating one. Are there plans to support ansible 2.11? Thank you.

```
ERROR! Your Ansible version (2.11.0) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 10).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/dw/mitogen/issues/
```

**Comment by upekkha** [comment]
I found the following [patch](https://github.com/upekkha/mitogen/commit/37e33106ae4b3077be6b7ae9b06aae3e220f0cdd) to provide minimal support for ansible-core 2.11. My test playbook seems to work with ansible 4.0.0 (ansible-core 2.11.0), as well as ansible 3.4.0 (ansible-base 2.10.9), but I did not test older Ansible versions.

The main issue was that Ansible no longer exposes the options of the ssh connection plugin as play_context attributes.

https://github.com/ansible/ansible/pull/73708

**Comment by apple4ever** [comment]
@upekkha That patched worked for me too! You should submit a PR.

**Comment by davidmehren** [comment]
Unfortunately, the patch seems to ignore `ansible_ssh_common_args` which I set at group level, so my SSH jump host stops working.

**Comment by upekkha** [comment]
Good catch. Looks like one also has to [pass the variables as argument](https://github.com/upekkha/mitogen/commit/26609a3a43b6a404e9d503b27ba72ae454528999) to allow for config overrides. If this also works for you, I will update the PR.

**Comment by davidmehren** [comment]
Thanks for taking a look. I had to remove the access to the second `vars` sub-dict, so https://github.com/mitogen-hq/mitogen/pull/841/files#diff-a98bb8f749289d5b203cc23fbe75d1a1e651bf8b20a80d4e3a7598129f1a4472R467 looks like this for me:
```python
variables = self._task_vars.get("vars", {})
```
With `self._task_vars["vars"].get("vars", {})` I would only get an empty dict. I have `ansible==4.0.0` and `ansible-core==2.11.1`.

**Comment by upekkha** [comment]
You are right. I reverted the additional "vars" key. I did my test by adding a `ansible_ssh_args` variable to a host directly inside the inventory. After my first commit I got somehow confused by the different syntax for groups (with `vars:`) and hosts (without `vars:`).

**Comment by sfriedrichs-broadsoft** [comment]
As far as I know there is still no update for mitogen. You have to stick closer to the Ansible releases! Workarounds are not good enough here. Please release 2.11.(.2) support short term!

**Comment by GhostLyrics** [comment]
Is there anything left to do for the patch @upekkha provided? I was wondering if something is blocking a merge.

**Comment by ohdearaugustin** [comment]
I also use that patch, but I always get errors with the apt module.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module '__main__' has no attribute '_module_fqn'
fatal: [<reacted>-mon]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  module_stderr: |-
    Traceback (most recent call last):
      File "master:/<reaced>/<reacted>/mgit/mitogen/ansible_mitogen/runner.py", line 975, in _run
        self._run_code(code, mod)
      File "master:/home/<reacted>/<reacted>/mitogen/ansible_mitogen/runner.py", line 939, in _run_code
        exec(code, vars(mod))
      File "master:/usr/lib/python3.9/site-packages/ansible/modules/apt.py", line 1310, in <module>
      File "master:/usr/lib/python3.9/site-packages/ansible/modules/apt.py", line 1114, in main
      File "master:/usr/lib/python3.9/site-packages/ansible/module_utils/common/respawn.py", line 39, in respawn_module
        payload = _create_payload()
      File "master:/usr/lib/python3.9/site-packages/ansible/module_utils/common/respawn.py", line 76, in _create_payload
        module_fqn = sys.modules['__main__']._module_fqn
    AttributeError: module '__main__' has no attribute '_module_fqn'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
Ansible Version:

```

Interestingly is the patch forcing to use as interpreter python3 (/usr/bin/python3) and it is just ignoring `interpreter_python = /usr/bin/python` used in ansibe.cfg.

**Comment by GhostLyrics** [comment]
@ohdearaugustin  Just out of curiousity, could you try `ansible.builtin.apt` instead of `apt`?

> ```
> - name: install prometheus
>   apt:
>     name: prometheus
>     state: present
> ```

**Comment by ohdearaugustin** [comment]
@GhostLyrics Tried it with `ansible.builtin.apt` and I get the exact same issue. If it helps I can post a more verbose error message.

**Comment by upekkha** [comment]
I can confirm that setting `interpreter_python = /usr/bin/python` in ansible.cfg gets ignored by mitogen, while setting `ansible_python_interpreter: /usr/bin/python` at the level of host/group vars seems to work. Nevertheless I get the impression that this is not related to the linked patch, but some other change in Ansible breaking the interpreter discovery of mitogen. Hopefully one of the mitogen developers joins in at some point to shed some light on the future support of Ansible 2.11+.

**Comment by GhostLyrics** [comment]
@moreati Thank you so much for getting this done. 🙏
