### ISSUE TITLE
Download URL broken: https://networkgenomics.com/try/mitogen-0.2.9.tar.gz

### ISSUE THREAD

**Issue by DanVanAtta** [mitogen-hq/mitogen#856]
Previously 'https://networkgenomics.com/try/mitogen-0.2.9.tar.gz' would download the mitogen tar.gz file. 

Sometime somewhat recently that URL now redirects to https://mitogen.networkgenomics.com/

This breaks build pipelines that have the above URL baked in and breaks the 'download mitogen' link on: https://mitogen.networkgenomics.com/ansible_detailed.html

**Comment by dw** [comment]
Thanks for reporting this, the redirects should be functioning correctly now.
