### ISSUE TITLE
Release 0.3.0?

### ISSUE THREAD

**Issue by DaVince** [mitogen-hq/mitogen#888]
I see a tag 0.3.0, originating straight from a PR named "Release 0.3.0" (#862) from October 28. But there is no actual release of this on the Releases page.

What's going on here? Also, if I do want to use that release 0.3.0, is cloning the repo enough to start using it? (Edit: that's a yes, which is nice.)

**Comment by moreati** [comment]
Like most Python projects Mitogen releases are made on pypi.org/p/mitogen. We don't use the github release mechanism.

**Comment by DaVince** [comment]
Thanks for letting me know. It might be a good idea to remove the [existing Github releases](https://github.com/mitogen-hq/mitogen/releases) then.
