### ISSUE TITLE
Expired certificate for Networkgenomics.com

### ISSUE THREAD

**Issue by ixe013** [mitogen-hq/mitogen#900]
It is not possible to download Mitogen anymore from our pipeline, because of an [expired certificate on https://networkgenomics.com/](https://networkgenomics.com/try/mitogen-0.2.9.tar.gz).

Can you make sure your webserver uses the [newly issued Let's Encrypt certificate you got](https://crt.sh/?id=6057461341)? 

Some webservers need to be restarted to use the new certificate...

**Comment by HonkinWaffles** [comment]
Can confirm that the certificate expired on the 2nd of Feb. Would like to incorporate the project into our workflow but need a valid cert to download.

**Comment by ixe013** [comment]
Well the certificate is public. You can [download it from the certificate transparency website](https://crt.sh/?id=6057461341). Look for a link at the bottom of the left hand column, or [use this one](https://crt.sh/?id=6057461341). The same private key was used so you can just replace the old certificate witht the new one.

But it will break again in 2 months (April 26, 2022). I think there is something wrong with your Let's Encrypt configuration, the certificate should renew automatically.

[networkgenomics.crt.txt](https://github.com/mitogen-hq/mitogen/files/8051834/networkgenomics.crt.txt)

**Comment by vrms** [comment]
this seems to be an ongoing problem https://github.com/mitogen-hq/mitogen/issues/914

**Comment by jfcabral** [comment]
From what I can see, the certificate is valid atm, so this issue can be closed
![imagem](https://github.com/mitogen-hq/mitogen/assets/1048422/9d3c39ea-99ce-4ef7-aaaf-ad39fcb4c17e)

right @ixe013 ?

**Comment by ixe013** [comment]
Yes, it can be closed.

**Comment by jfcabral** [comment]
As the author of the issue, I believe you should be able to close it, right @ixe013?
(I'm not a maintainer ;) )
