### ISSUE TITLE
Mitogen Download Broken SSL Cert

### ISSUE THREAD

**Issue by mattjamesaus** [mitogen-hq/mitogen#914]
The mitogen website is serving a bad SSL cert for the mitogen download, couldn't find a relevant contact link to point it out.

```
❯ curl -I https://networkgenomics.com/try/mitogen-0.2.9.tar.gz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by vrms** [comment]
this seems to be a repeating problem. see https://github.com/mitogen-hq/mitogen/issues/900

**Comment by jfcabral** [comment]
From what I can see, the certificate is valid atm, so this issue can be closed
![imagem](https://github.com/mitogen-hq/mitogen/assets/1048422/9d3c39ea-99ce-4ef7-aaaf-ad39fcb4c17e)

right @mattjamesaus ?

**Comment by mattjamesaus** [comment]
Would seem like it, we can close this out now

**Comment by jfcabral** [comment]
As the author of the issue, I believe you should be able to close it, right @mattjamesaus?
(I'm not a maintainer ;) )
