### ISSUE TITLE
Ansible core 2.13 support

### ISSUE THREAD

**Issue by uumas** [mitogen-hq/mitogen#929]
Ansible core 2.13 dropped so mitogen needs to be updated again

```
ERROR! Your Ansible version ((2, 13, 0)) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 12).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/mitogen-hq/mitogen/issues/
```

**Comment by oxy-arnoldasb** [comment]
Same after
$ brew upgrade ansible

✗ ansible --version
ansible [core 2.13.1]

ERROR! Your Ansible version ((2, 13, 1)) is too recent

**Comment by cfarrell987** [comment]
Any update when this commit will be merged and released? This is a blocker for implementing Mitogen.

**Comment by gertvdijk** [comment]
@cfarrell987 The PR is still a draft. https://github.com/mitogen-hq/mitogen/pull/933

Perhaps comment _there_ on the progress of it? 😃

**Comment by dr460nf1r3** [comment]
Quick question, after updating to the most recent commit I'm still getting
```
[WARNING]: Unhandled error in Python interpreter discovery for host esxi-web: builtins.ModuleNotFoundError:
The Mitogen master process was unable to serve 'ansible_mitogen.target'. It may be a native Python extension,
or it may be missing entirely. Check the importer debug logs on the master for more information.   File
"<stdin>", line 3698, in _dispatch_one   File "<stdin>", line 3685, in _parse_request   File "<stdin>", line
682, in import_module   File "<stdin>", line 1521, in load_module

TASK [Gathering Facts] ***************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   File "<stdin>", line 1521, in load_module
fatal: [host]: FAILED! =>
msg: Unexpected failure during module execution.
stdout: ''
```

The ansible version used is 
```
ansible [core 2.13.2]
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/nico/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.10/site-packages/ansible
ansible collection location = /home/nico/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
jinja version = 3.1.2
libyaml = True
```
What could possibly cause this?

**Comment by moreati** [comment]
> What could possibly cause this?

I don't know, and to my knowledge it doesn't happen in the integration tests. Could you raise a new issue, with a minimal playbook that reproduces the error?

**Comment by dr460nf1r3** [comment]
Yes of course, thanks!

**Comment by oxy-arnoldasb** [comment]
with latest mitogen #929 released, still getting some weird error :/

```
ok: [server1] => (item=../ansible/roles/common/templates/etc/firewall.d/00-flush.j2)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: mitogen.core.Error: An attempt was made to enqueue a message with a Broker that has already exitted. It is likely your program called Broker.shutdown() too early.
fatal: [server1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by gertvdijk** [comment]
@oxy-arnoldasb Your error seems unrelated to this issue of 2.13 support.
I found #822, #663 and possibly #925 that seem similar.

**Comment by upekkha** [comment]
The Broker error is also making many of our playbooks fail at random tasks, as soon as I upgrade from ansible 5.10.0 (ansible-core 2.12.7) to ansible 6.2.0 (ansible-core 2.13.2) - for the same mitogen at current master 8cda5f55375e3c5caa77d900d1bfa90c5fea0094.

I can confirm the [statement](https://github.com/mitogen-hq/mitogen/issues/925#issuecomment-1164798186) from #925 that commenting out the `self.close()` [here](https://github.com/mitogen-hq/mitogen/blob/8cda5f55375e3c5caa77d900d1bfa90c5fea0094/ansible_mitogen/connection.py#L531) seems to fix the issue. So it may well be that the work-around that was needed back in 2014 (commit 3584084be6556acc76e7279bef227945a73da086) is becoming counter-productive for newer ansible releases.

**Comment by arhue** [comment]
@upekkha I tried with Ansible 6.3.0 and python 3.8. Getting similar issue with use of loop while copying template files to destination in particular.

**Comment by yasharne** [comment]
same here:
```
ERROR! Your Ansible version ((2, 13, 5)) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 12).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/mitogen-hq/mitogen/issues/
```
mitogen version: 0.3.3
