### ISSUE TITLE
Ansible-core 2.14 support

### ISSUE THREAD

**Issue by vanyasvl** [mitogen-hq/mitogen#974]
Ansible-core 2.14.0 was released yesterday.

Please add support to mitogen.

Thanks.

**Comment by arrfab** [comment]
you're aware that  #966 is still open so afaik mitogen doesn't support (yet) ansible-core 2.13 ... haven't checked in a while but still the reason why I stick with ansible-core 2.12 for the moment

**Comment by vanyasvl** [comment]
> you're aware that #966 is still open so afaik mitogen doesn't support (yet) ansible-core 2.13 ... haven't checked in a while but still the reason why I stick with ansible-core 2.12 for the moment

Yep, so Mitogen project looks rather dead than alive

**Comment by apple4ever** [comment]
> Yep, so Mitogen project looks rather dead than alive

It seems so. I filed #945 four months ago and we had to stop using it because of that. 

It's a shame because it was a great project and made Ansible so fast. But that's how it goes with open source. I'd love to contribute since I do know Python but I don't know enough to help in a project like this.

**Comment by beinbliss** [comment]
> > Yep, so Mitogen project looks rather dead than alive
> 
> It seems so. I filed #945 four months ago and we had to stop using it because of that. Nobody has even commented to try to help.
> 
> It's a shame because it was a great project and made Ansible so fast. But that's how it goes with open source. I'd love to contribute since I do know Python but I don't know enough to help in a project like this.

Actually the "fast" part should be inside ansible core. Why ansible core does not implement it is hard to understand.

**Comment by opoplawski** [comment]
FWIW - just bumping ANSIBLE_VERSION_MAX to (2, 14) allows my plays to run. YMMV.

**Comment by badfiles** [comment]
```
TASK [community.zabbix.zabbix_agent : Do a yum clean] ****************************************************************************************************************************************
fatal: [*mx.*.*]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: executable, argv, removes, chdir, _uses_shell, stdin_add_newline, stdin, strip_empty_ends, creates, _raw_params."}
```
it's broken with 2.14

**Comment by nerijus** [comment]
> it's broken with forced 2.14 support
I have it without mitogen, removing `warn` helps, so it is not a mitogen problem.

**Comment by NikitaCOEUR** [comment]
> FWIW - just bumping ANSIBLE_VERSION_MAX to (2, 14) allows my plays to run. YMMV.

I try it but gather fact failed with this..
So force use Ansible-core 2.12... (Ansible 5)

**Comment by arrfab** [comment]
> 



> FWIW - just bumping ANSIBLE_VERSION_MAX to (2, 14) allows my plays to run. YMMV.

Just curious .. myself I'd need to bump to 2.14 but mitogen is still the only thing that doesn't work with it .. can you elaborate on the ANSIBLE_VERSION_MAX ? you mean directly in mitogen and so bypass all checks ?

**Comment by opoplawski** [comment]
> > FWIW - just bumping ANSIBLE_VERSION_MAX to (2, 14) allows my plays to run. YMMV.
> 
> Just curious .. myself I'd need to bump to 2.14 but mitogen is still the only thing that doesn't work with it .. can you elaborate on the ANSIBLE_VERSION_MAX ? you mean directly in mitogen and so bypass all checks ?

Yes.

**Comment by amarao** [comment]
I ack that, I've run a rather big codebase on ansible-2.14 and mitogen with patched version restriction and it just worked.

May be we can allow users to override this restriction via environment variable or some other mechanism. End-user patching is madness.

**Comment by arrfab** [comment]
Yes, or better : have a new mitogen tag/release that would have that ? Wondering if a mitogen dev can consider this, assuming that there were enough feedback about it working with ansible-core 2.14 (or list what would still be problematic, etc)

**Comment by krystian-panek-wttech** [comment]
how about introducing some configuration parameter here https://github.com/mitogen-hq/mitogen/blob/8cda5f55375e3c5caa77d900d1bfa90c5fea0094/ansible_mitogen/loaders.py#L54 for skipping that check /  allowing to use Ansible Mitogen with Ansible not officially/tested/supported version? of course at own risk...

from my perspective using Mitogen is very valuable and it just decreases Ansible execution time by minutes for free it is just very sad that right now there is no Mitogen version officially compatible with any maintained Ansible version.

The most recent version of Ansible that works with Mitogen I found is 5.10.0:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/81212505/224650119-a0b1da36-f4ed-45a9-835e-e5d90cc28925.png">

I have no Python skills and I am unable to help but if there is sb that could help with making Mitogen up-to-date with some recent version of Ansible ... then I will not hesitate and buy such a person a beer ;)

**Comment by HOSTED-POWER** [comment]
PS: I forked current repo and changed `ANSIBLE_VERSION_MAX = (2, 14)` in the loaders.py

Added it inside our execution environment and it seems to run fine so far

**Comment by djuarezg** [comment]
Any possibility to bump he version max?

**Comment by amarao** [comment]
https://galaxy.ansible.com/serverscom/mitogen

It will patch it for you and upatch back automatically.

**Comment by ksyblast** [comment]
> PS: I forked current repo and changed `ANSIBLE_VERSION_MAX = (2, 14)` in the loaders.py
> 
> Added it inside our execution environment and it seems to run fine so far

It seems that delegate_to tasks are broken. Or does it work for anybody?

**Comment by GhostLyrics** [comment]
Due to ongoing, long-standing problems with catching up with newer ansible versions, my employer decided to abandon mitogen. We'll miss the speed but the constant tinkering so that it might work "well enough" without spitting traces onto stdout and seemingly work only for the next Ansible minor to make incompatible again made us give up on it completely. ☹️ 

And to be perfectly honest, the frequency of things being merged to `master` (let me know if you use mainly use a different branch?) is not inspiring confidence.
<img width="431" alt="Screenshot 2023-07-07 at 13 43 48" src="https://github.com/mitogen-hq/mitogen/assets/259911/626b4869-484e-4c34-ad3e-55f82b4fb5f7">

**Comment by krystian-panek-wttech** [comment]
maintaining VMs these days is a niche ... so maintaining tools for maintaining VMs is even super niche ;) that's why I guess Mitogen has no sufficient support and only volunteers could push it forward.

**Comment by quickchase** [comment]
seems ansible-core 2.13 is now EoL, based on [ansible-core-support-matrix](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix)

**Comment by djuarezg** [comment]
> > PS: I forked current repo and changed `ANSIBLE_VERSION_MAX = (2, 14)` in the loaders.py
> > Added it inside our execution environment and it seems to run fine so far
> 
> It seems that delegate_to tasks are broken. Or does it work for anybody?

Same in here... We cannot upgrade Ansible because if we do we need to remove Mitogen... And given previous versions are already on EOL this should be given a bit of attention.

**Comment by KatrinIhler** [comment]
Hate to beat a dead horse, but I, too, would be very interested to see compatibility with Ansible 2.14. We are maintaining an Open Source software with lots of configuration files on VM clusters for our clients and the speedup with Mitogen used to be considerable. Very sad we can't use it anymore. .__.

**Comment by opoplawski** [comment]
> > > PS: I forked current repo and changed `ANSIBLE_VERSION_MAX = (2, 14)` in the loaders.py
> > > Added it inside our execution environment and it seems to run fine so far
> > 
> > 
> > It seems that delegate_to tasks are broken. Or does it work for anybody?
> 
> Same in here... We cannot upgrade Ansible because if we do we need to remove Mitogen... And given previous versions are already on EOL this should be given a bit of attention.

Is the delegate_to related to any of the other delegate_to issues reported to mitogen?  A basic delegate_to task works for me with ansible 2.15.3 and a patched version of mitogen to allow that version.

**Comment by moreati** [comment]
PR https://github.com/mitogen-hq/mitogen/pull/1017 adds Ansible 7 (core 2.14) support. Please try it and reply with any good or bad results. If all is well this will go into master, and then release 0.3.6. Sorry for the long wait.

**Comment by YanFenGuo** [comment]
> PR #1017 adds Ansible 7 (core 2.14) support. Please try it and reply with any good or bad results. If all is well this will go into master, and then release 0.3.6. Sorry for the long wait.

Good to know there is a PR for 2.14, pls consider 2.15 as well https://github.com/mitogen-hq/mitogen/issues/1021

**Comment by moreati** [comment]
Mitogen 0.3.6 is now out.
