### ISSUE TITLE
Ansible 2.10.17 is still not supported

### ISSUE THREAD

**Issue by shanmugaraj82** [mitogen-hq/mitogen#979]
ERROR! Your Ansible version (2.10.17) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 9).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/dw/mitogen/issues/

**Comment by vanyasvl** [comment]
Use v0.3.x for Ansible 2.10+

**Comment by dahse89** [comment]
> Use v0.3.x for Ansible 2.10+

I tried that but still get the message above from ansible

```
> pip list | grep mitogen
mitogen            0.3.3

> ansible-playbook [..]
ERROR! Your Ansible version (2.14.0) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 9).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/dw/mitogen/issues/
```

**Comment by saibug** [comment]
> Use v0.3.x for Ansible 2.10+

but this version is still not released :(

**Comment by vanyasvl** [comment]
> > Use v0.3.x for Ansible 2.10+
> 
> but this version is still not released :(

Released, 0.3.3 is the latest version https://pypi.org/project/mitogen/

**Comment by saibug** [comment]
> > > Use v0.3.x for Ansible 2.10+
> > 
> > 
> > but this version is still not released :(
> 
> Released, 0.3.3 is the latest version https://pypi.org/project/mitogen/

ok , missed information. 
i would like to test it with ansible >= 2.12 version

**Comment by lethargosapatheia** [comment]
I think you should probably fix the documentation which pops up as the first result in google then:
https://mitogen.networkgenomics.com/ansible_detailed.html

I saw that mitogen was still actively developed, and I got the error that I couldn't use a higher version than 2.9 (eol in May 2022). I'm using 2.14.3 now. I'm still not sure how I'm supposed to install mitogen and integrate it with ansible though :)

**Comment by amarao** [comment]
Take mitogen from master, patch version requirement, and it works with 2.14. More or less, as it was before (some bleeding corner-cases, but you get used to them pretty quickly).

**Comment by lethargosapatheia** [comment]
Yes, thank you, I was eventually able to use the latest stable version of mitogen and downgrade ansible to 2.10 (latest from ubuntu 22.04). I don't need the latest ansible version.

**Comment by stianlagstad** [comment]
In case it helps others: I was able to use mitogen 0.3.3 with ansible-core 2.12.10.

**Comment by moreati** [comment]
The outdated website is #1008. Mitogen 0.3.4 (current release) supports Ansible 2.10 -Ansible 6, #977 and/or #1017 will add Ansible 7. Sorry for the confusion and the long wait.

**Comment by huyz** [comment]
@moreati I'm new to Mitogen so I may not be aware of how the release cycles work. The current Ansible version seems to be 8, with core at 2.15.  When is Mitogen expected to support the current release?
