### ISSUE TITLE
Add compatibility for Ansible 6.X.Y

### ISSUE THREAD

**Issue by djuarezg** [mitogen-hq/mitogen#996]
As per title says, it would be great if this was compatible with latest versions of Ansible 6.x.y

**Comment by amarao** [comment]
Try to use https://galaxy.ansible.com/serverscom/mitogen. It autopatches mitogen to be compatible with Ansible-core 2.14/2.15 (ansible 7/8).

**Comment by amarao** [comment]
It's not 'me', I just work there.

**Comment by moreati** [comment]
Fixed by #929

**Comment by moreati** [comment]
Releases are on PyPI https://pypi.org/project/mitogen/
